import Head from "next/head";
import Image from "next/image";
import CountryCard from "../components/CountryCard";

export default function Home({ data }) {
  const country = data.map((country, i) => (
    <CountryCard
      key={i}
      flagImg={country.flags.png}
      countryName={country.name.official}
      pop={country.population}
      region={country.region}
      capital={country.capital}
    />
  ));
  console.log(data[0].capital);
  // console.log(countries);
  return (
    <div className="container min-h-screen mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-1 gap-8 mt-4 md:grid-cols-2 lg:grid-cols-4">
        {data.length > 0 ? country : <h1>Loading</h1>}
      </main>
    </div>
  );
}
export const getStaticProps = async (ctx) => {
  const res = await fetch("https://restcountries.com/v3.1/all");
  const data = await res.json();

  return {
    props: {
      data: data,
    },
  };
};
